# General 
export ALLOW_MISSING_DEPENDENCIES=true
export LC_ALL="C.UTF-8"

# OrangeFox build settings & info
export FOX_USE_TWRP_RECOVERY_IMAGE_BUILDER=1
export OF_NO_TREBLE_COMPATIBILITY_CHECK=1
export TARGET_DEVICE_ALT="RMX1991,RMX1991CN,RMX1992,RMX1993"
export OF_SUPPORT_OZIP_DECRYPTION=1
export FOX_DELETE_INITD_ADDON=1
export TARGET_ARCH=arm64

# OrangeFox binary files
export FOX_REPLACE_BUSYBOX_PS=1
export FOX_REPLACE_TOOLBOX_GETPROP=1
export FOX_USE_TAR_BINARY=1
export FOX_USE_XZ_UTILS=1
export FOX_USE_SED_BINARY=1
export OF_ENABLE_LPTOOLS=1
	
# OrangeFox patches
export OF_PATCH_AVB20=1

# OTA
export OF_KEEP_DM_VERITY=1
export OF_FIX_OTA_UPDATE_MANUAL_FLASH_ERROR=1
export OF_OTA_BACKUP_STOCK_BOOT_IMAGE=1
export OF_SUPPORT_ALL_BLOCK_OTA_UPDATES=1
export OF_DISABLE_MIUI_OTA_BY_DEFAULT=1

# OrangeFox settings
export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
export OF_SCREEN_H=2340
export OF_STATUS_H=80
export OF_STATUS_INDENT_LEFT=48
export OF_STATUS_INDENT_RIGHT=48
export OF_ALLOW_DISABLE_NAVBAR=0
export FOX_ADVANCED_SECURITY=1
export OF_FLASHLIGHT_ENABLE=1
export OF_USE_GREEN_LED=0
export FOX_DELETE_AROMAFM=1
export OF_ENABLE_USB_STORAGE=1
export OF_NO_SPLASH_CHANGE=1
